name: HAL SPARKS
favicon: null
layout_spectrum: 0.84691
typography_spectrum: 0.8584229
title: Hal Sparks
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FEFEFE'
    - '#060405'
    - '#431E16'
    - '#786D5C'
    - '#BCB6B4'
  brandStrength: 0.75
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
